### ISSUE TITLE
ImportError: No module named lxml.builder

### ISSUE THREAD

**Issue by natea** [django-oscar/django-oscar-mws#2]
It appears that lxml is required but not defined as a dependency in setup.py:

```
python slstore/manage.py syncdb
/Users/nateaune/.virtualenvs/smallslivestore/lib/python2.7/site-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Traceback (most recent call last):
  File "slstore/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nateaune/.virtualenvs/smallslivestore/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/nateaune/.virtualenvs/smallslivestore/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/nateaune/.virtualenvs/smallslivestore/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/nateaune/.virtualenvs/smallslivestore/lib/python2.7/site-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/Users/nateaune/.virtualenvs/smallslivestore/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/Users/nateaune/.virtualenvs/smallslivestore/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/Users/nateaune/.virtualenvs/smallslivestore/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/Users/nateaune/.virtualenvs/smallslivestore/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/Users/nateaune/.virtualenvs/smallslivestore/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/Users/nateaune/.virtualenvs/smallslivestore/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/nateaune/.virtualenvs/smallslivestore/src/django-oscar-mws/oscar_mws/models.py", line 1, in <module>
    from . import abstract_models as am
  File "/Users/nateaune/.virtualenvs/smallslivestore/src/django-oscar-mws/oscar_mws/abstract_models.py", line 10, in <module>
    from lxml.builder import E
ImportError: No module named lxml.builder
```

**Comment by roadsideseb** [comment]
Well spotted, thanks. I've updated the `setup.py` accordingly.

**Comment by STANAPI** [comment]
> Well spotted, thanks. I've updated the `setup.py` accordingly.

How to update in setup.py?
